apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homefinanceclub
  namespace: lf-prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - homefinanceclub.com
        - www.homefinanceclub.com
      secretName: homefinanceclub-tls
  rules:
    - host: homefinanceclub.com
      http:
        paths:
          - path: /serviceroom/api/
            pathType: Prefix
            backend:
              service:
                name: serviceroom-backend
                port:
                  number: 80
          - path: /serviceroom/
            pathType: Prefix
            backend:
              service:
                name: serviceroom-frontend
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: leadapp-api
                port:
                  number: 80
          - path: /wapp/
            pathType: Prefix
            backend:
              service:
                name: leadapp-widget
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hfc-wp
                port:
                  number: 80
