apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leadsfilter
  namespace: lf-prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - leadsfilter.com
        - www.leadsfilter.com
      secretName: leadsfilter-tls
  rules:
    - host: leadsfilter.com
      http:
        paths:
          - path: /admin2
            pathType: Prefix
            backend:
              service:
                name: leadstore-admin
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: leadstore-api
                port:
                  number: 80
          - path: /portal
            pathType: Prefix
            backend:
              service:
                name: leadstore-portal
                port:
                  number: 80
          - path: /shared
            pathType: Prefix
            backend:
              service:
                name: leadstore-shared
                port:
                  number: 80
          - path: /serviceroom/admin
            pathType: Prefix
            backend:
              service:
                name: serviceroom-backend
                port:
                  number: 80
          - path: /serviceroom/api
            pathType: Prefix
            backend:
              service:
                name: serviceroom-backend
                port:
                  number: 80
          - path: /serviceroom
            pathType: Prefix
            backend:
              service:
                name: serviceroom-frontend
                port:
                  number: 80
          - path: /corp
            pathType: Prefix
            backend:
              service:
                name: leadsfilter-corp-wp
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: leadstore-landing
                port:
                  number: 80
