apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocoder
  namespace: lf-prod
spec:
  replicas: 0
  selector:
    matchLabels:
      app: geocoder
  template:
    metadata:
      labels:
        app: geocoder
    spec:
      containers:
        - name: geocoder
          image: alpine:3.19.0
          workingDir: /app
          command:
            - sh
            - -c
            - chmod +x geocoder-api && ./geocoder-api
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: geocoder
            - name: POSTGRES_USER
              value: geocoder
            # --- secret 'geocoder': POSTGRES_PASSWORD, API_KEYS ---
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geocoder
                  key: POSTGRES_PASSWORD
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: geocoder
                  key: API_KEYS
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          hostPath:
            path: /data/lf-prod/geocoder/app
            type: Directory
