apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocoder
  namespace: lf-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geocoder
  template:
    metadata:
      labels:
        app: geocoder
    spec:
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: leadsfilter-n1
      containers:
        - name: geocoder
          image: alpine:3.19.0
          workingDir: /app
          command:
            - sh
            - -c
            - chmod +x geocoder-api && ./geocoder-api
          # --- secret 'geocoder': POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, API_KEYS ---
          envFrom:
            - secretRef:
                name: geocoder
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          hostPath:
            path: /data/lf-prod/geocoder
            type: Directory
