apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadstore-api
  namespace: lf-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leadstore-api
  template:
    metadata:
      labels:
        app: leadstore-api
    spec:
      enableServiceLinks: false
      containers:
        - name: leadstore-api
          image: mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim
          workingDir: /app
          command:
            - bash
            - -c
            - chmod +x LeadStore.API && ./LeadStore.API
          env:
            - name: HTTP_PATH_BASE
              value: /api
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: leadstore-common
            - secretRef:
                name: leadstore
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          hostPath:
            path: /data/lf-prod/leadstore-api
            type: Directory
