apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - capacitor/
  - cert-manager/
  - gateway-api-crds/
  - nginx-gateway-fabric/
  - reflector/
  - repositories/
  - openvpn/
  - backrest/
