apiVersion: v1
kind: ConfigMap
metadata:
  name: hfc-wp-php-config
  namespace: lf-prod
data:
  opcache.ini: |
    opcache.jit_buffer_size=64M
    opcache.max_accelerated_files=10000
    opcache.interned_strings_buffer=16
    opcache.revalidate_freq=60
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hfc-wp-valkey-config
  namespace: lf-prod
data:
  valkey.conf: |
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    save ""
