apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: ecr-config-leadsfilter
data:
  REGION: "us-east-2"
  ECR_REGISTRY: "925375122018.dkr.ecr.us-east-2.amazonaws.com"
  SECRET_NAME: "ecr-credentials-leadsfilter"
