apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ecr-credentials-sync-cm.yaml
  - ecr-credentials-sync-cj.yaml
  - serviceroom-backend-ir.yaml
  - serviceroom-backend-prod-ip.yaml
  - serviceroom-backend-iua.yaml
