apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ecr-credentials-sync-configmap.yaml
  - ecr-credentials-sync-cronjob.yaml
  - serviceroom-backend-imagerepository.yaml
  - serviceroom-backend-prod-imagepolicy.yaml
