apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: serviceroom-frontend-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: serviceroom-frontend
  filterTags:
    pattern: '^[a-f0-9]+-(?P<ts>\d{4}-\d{2}-\d{2}\.\d{6})-prod$'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc
