apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-lf-stage
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/lf-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
