apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager-issuer
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/cluster/cert-manager-issuer
  dependsOn:
    - name: infra-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
