apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - apps-lf-stage.yaml
  - apps-lf-prod.yaml
  - infra-lf-stage.yaml
  - infra-lf-prod.yaml
  - infra-gateway-api-crds.yaml
  - infra-cluster.yaml
  - infra-cert-manager-issuer.yaml
