apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadsfilter-corp-wp
  namespace: lf-prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: leadsfilter-corp-wp
  template:
    metadata:
      labels:
        app: leadsfilter-corp-wp
    spec:
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: leadsfilter-n1
      containers:
        - name: mariadb
          image: mariadb:11.4-noble
          # --- secret 'leadsfilter-corp-wp': MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD, MYSQL_RANDOM_ROOT_PASSWORD ---
          envFrom:
            - secretRef:
                name: leadsfilter-corp-wp
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 400Mi
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
            - name: tmp-host
              mountPath: /tmp_host
        - name: apache
          image: wordpress:6.5-php8.3-apache
          # --- secret 'leadsfilter-corp-wp': WORDPRESS_DB_HOST, WORDPRESS_DB_USER, WORDPRESS_DB_NAME,
          #     WORDPRESS_DB_PASSWORD, WORDPRESS_SMTP_HOST, WORDPRESS_SMTP_PORT,
          #     WORDPRESS_SMTP_FROM, WORDPRESS_SMTP_FROM_NAME ---
          envFrom:
            - secretRef:
                name: leadsfilter-corp-wp
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 512Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /var/www/html
            - name: apache-config
              mountPath: /etc/apache2/apache2.conf
            - name: tmp-host
              mountPath: /tmp_host
      volumes:
        - name: db
          hostPath:
            path: /data/lf-prod/leadsfilter-corp-wp/db
            type: Directory
        - name: html
          hostPath:
            path: /data/lf-prod/leadsfilter-corp-wp/www/html
            type: Directory
        - name: apache-config
          hostPath:
            path: /data/lf-prod/leadsfilter-corp-wp/apache2/apache2.conf
            type: File
        - name: tmp-host
          hostPath:
            path: /data/lf-prod/leadsfilter-corp-wp/tmp_host
            type: Directory
