apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: lf-prod
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: leadsfilter-n1
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: info@leadsfilter.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: not-a-real-password--kqwrxi3hv8987hlstgklfwgfwgrh
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 256Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
            - name: servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: data
          hostPath:
            path: /data/lf-prod/pgadmin
            type: Directory
        - name: servers
          configMap:
            name: pgadmin-servers
