apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vicdevcs@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - selector:
          dnsNames:
            - homefinanceclub.com
            - www.homefinanceclub.com
        http01:
          ingress:
            ingressClassName: nginx-hfc
      - http01:
          ingress:
            ingressClassName: nginx
