apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadstore-cron
  namespace: lf-prod
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: leadstore-cron
  template:
    metadata:
      labels:
        app: leadstore-cron
    spec:
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: leadsfilter-n1
      containers:
        - name: leadstore-cron
          image: mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim
          workingDir: /app
          command:
            - bash
            - -c
            - chmod +x LeadStore.Cron && ./LeadStore.Cron
          env:
            - name: HTTP_PATH_BASE
              value: /api
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: leadstore-common
            - secretRef:
                name: leadstore
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          hostPath:
            path: /data/lf-prod/leadstore-cron
            type: Directory
