apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadstore-shared
  namespace: lf-prod
spec:
  replicas: 0
  selector:
    matchLabels:
      app: leadstore-shared
  template:
    metadata:
      labels:
        app: leadstore-shared
    spec:
      containers:
        - name: leadstore-shared
          image: nginx:1.25-alpine-slim
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
            - name: wwwroot
              mountPath: /app
      volumes:
        - name: nginx-config
          hostPath:
            path: /data/lf-prod/leadstore-shared/nginx/nginx.conf
            type: File
        - name: wwwroot
          hostPath:
            path: /data/lf-prod/leadstore-shared/wwwroot
            type: Directory
