apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadstore-admin
  namespace: lf-prod
spec:
  replicas: 0
  selector:
    matchLabels:
      app: leadstore-admin
  template:
    metadata:
      labels:
        app: leadstore-admin
    spec:
      containers:
        - name: leadstore-admin
          image: mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim-arm64v8
          workingDir: /app
          command:
            - bash
            - -c
            - chmod +x LeadStore.Admin && ./LeadStore.Admin
          env:
            - name: DOTNET_GCHeapHardLimit
              value: "0xA000000"
            - name: HTTP_PATH_BASE
              value: /admin2
          envFrom:
            - configMapRef:
                name: leadstore-common
            - secretRef:
                name: leadstore
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          hostPath:
            path: /data/lf-prod/leadstore-admin
            type: Directory
