apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadstore-portal
  namespace: lf-prod
spec:
  replicas: 0
  selector:
    matchLabels:
      app: leadstore-portal
  template:
    metadata:
      labels:
        app: leadstore-portal
    spec:
      containers:
        - name: leadstore-portal
          image: nginx:1.25-alpine-slim
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
            - name: app
              mountPath: /app
      volumes:
        - name: nginx-config
          hostPath:
            path: /data/lf-prod/leadstore-portal/nginx/nginx.conf
            type: File
        - name: app
          hostPath:
            path: /data/lf-prod/leadstore-portal/app
            type: Directory
