apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlenders
  namespace: lf-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zlenders
  template:
    metadata:
      labels:
        app: zlenders
    spec:
      enableServiceLinks: false
      containers:
        - name: zlenders
          image: alpine:3.19.0
          workingDir: /app
          command:
            - sh
            - -c
            - chmod +x zlenders-api && ./zlenders-api
          # --- secret 'zlenders': POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, API_KEYS ---
          envFrom:
            - secretRef:
                name: zlenders
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          hostPath:
            path: /data/lf-prod/zlenders
            type: Directory
