apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - leadstore-common/
  - postgres/
  - smtp-relay/
  - geocoder/
  - zlenders/
  - leadstore-admin/
  - leadstore-api/
  - leadstore-cron/
  - leadapp-api/
  - leadapp-widget/
  - leadstore-portal/
  - leadstore-landing/
  - leadstore-shared/
