apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - leadstore-common/
  - leadstore-migrate/
  - postgres/
  - smtp-relay/
  - geocoder/
  - zlenders/
  - leadstore-admin/
  - leadstore-api/
  - leadstore-cron/
  - leadapp-api/
  - leadapp-widget/
  - leadstore-portal/
  - leadstore-landing/
  - leadstore-shared/
  - wp-corp/
  - pgadmin/
  - serviceroom-postgres/
  - serviceroom-backend/
  - serviceroom-beat/
  - serviceroom-flower/
  - serviceroom-rabbitmq/
  - serviceroom-frontend/
  - serviceroom-worker/
  - hfc-wp/
  - ingress/
